parameters:
  webAppVarName: 'WebAppNameStaging'
  environment: "staging"

jobs:
- deployment: Deploy
  pool:
    vmImage: 'ubuntu-18.04'
  environment: ${{environment}}
  variables:
  - group: 'Release'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'Resource Manager - Tailspin - Space Game'
            appName: '$(${{webAppVarName}})'
            package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'